"""IBM Storage Scale policy listings: the rules cdm asks an administrator to run,
and the format of what comes back.

cdm never runs `mmapplypolicy` itself and never needs root (docs/roadmap.md,
Phase 2): `cdm policy` prints a script for an administrator to review and run,
the same advisory pattern as `cdm guide --schedule`. The script runs a LIST
rule with `-I defer`, which reads metadata and changes nothing, and wraps the
listing in a header and an end marker so `cdm import` can tell a complete
listing from a truncated one.

THE FORMAT, as measured on Storage Scale rather than assumed:

* Each line is `<inode> <gen> <snapid>  <fields> -- <path>`.
* `ESCAPE '%/'` percent-encodes the SHOW() fields as well as the path, so the
  fields arrive as one token with no spaces, and the first ` -- ` is always the
  separator. Paths are percent-encoded bytes with `/` left alone: spaces, tabs,
  `%` and UTF-8 all round-trip exactly.
* Times are UTC with microseconds, whatever the node's time zone.
* The policy SQL has no MIDNIGHT_SECONDS(), so times are shipped as text and
  converted here rather than computed in the rule.

Device and fileset names end up inside a shell script run as root and inside
policy SQL, so they are checked against a strict pattern, never escaped.
"""
from __future__ import annotations

import os
import re
import shlex
from dataclasses import dataclass
from datetime import datetime, timezone
from urllib.parse import unquote, unquote_to_bytes

FORMAT = "cdm-policy-listing v1"
LIST_NAME = "cdm"
FIELDS = ("size", "mtime", "atime", "ctime", "uid", "gid", "mode", "fileset",
          "pool", "nlink")
_SHOW = {"size": "VARCHAR(FILE_SIZE)", "mtime": "VARCHAR(MODIFICATION_TIME)",
         "atime": "VARCHAR(ACCESS_TIME)", "ctime": "VARCHAR(CHANGE_TIME)",
         "uid": "VARCHAR(USER_ID)", "gid": "VARCHAR(GROUP_ID)", "mode": "MODE",
         "fileset": "FILESET_NAME", "pool": "POOL_NAME", "nlink": "VARCHAR(NLINK)"}
END = "# end rows="
# First line of a sanitized fixture; scripts/check_raw_data.py requires it there.
SANITIZED = "# sanitized by cdm-sanitize v"

_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$")
_NODES = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._,-]{0,1023}$")


class PolicyError(ValueError):
    """A request that cannot be turned into a safe policy or script."""


class ListingError(ValueError):
    """A listing that is not a complete, well-formed cdm policy listing."""


def _check(kind: str, value: str, pattern: re.Pattern = _NAME) -> str:
    if not pattern.match(value):
        raise PolicyError(f"{kind} {value!r} is not a plain Storage Scale name "
                          f"(letters, digits, '.', '_', '-')")
    return value


# --- generating ---------------------------------------------------------------

def rules(fileset: str | None) -> str:
    """The policy: one LIST rule over one fileset, or the whole filesystem."""
    show = " || '|' || ".join(_SHOW[f] for f in FIELDS)
    scope = f" FOR FILESET('{_check('fileset', fileset)}')" if fileset else ""
    return (f"RULE EXTERNAL LIST '{LIST_NAME}' EXEC '' ESCAPE '%/'\n"
            f"RULE '{LIST_NAME}' LIST '{LIST_NAME}' DIRECTORIES_PLUS{scope}\n"
            f"  SHOW({show})\n")


def default_output(device: str, fileset: str | None) -> str:
    return f"{device}-{fileset}.list.raw" if fileset else f"{device}.list.raw"


def script(device: str, fileset: str | None, *, output: str | None = None,
           nodes: str | None = None, generator: str = "cdm") -> str:
    """A POSIX sh script that lists `fileset` (or all of `device`) for import.

    Run it as root on a node that mounts the filesystem. It writes OUTPUT, mode
    0600: a header (device, cluster, scope, the filesystem's atime setting,
    field order), the listing, and `# end rows=N`, via a temporary file renamed
    into place, so an interrupted run never leaves a listing that looks whole.
    """
    _check("device", device)
    if fileset is not None:
        _check("fileset", fileset)
    if nodes is not None:
        _check("node list", nodes, _NODES)
    output = output or default_output(device, fileset)
    if not output.endswith(".raw"):
        # .raw is what .gitignore and scripts/check_raw_data.py look for: a
        # listing names every file in its scope and must never be committed.
        raise PolicyError(f"output {output!r} must end in .raw")
    scope = f"fileset {fileset}" if fileset else "filesystem"
    n_flag = f" -N {nodes}" if nodes else ""
    return f"""#!/bin/sh
# Generated by {generator}: list the {scope} of IBM Storage Scale filesystem
# {device} for `cdm import --policy`.
#
# Review this script, then run it as root on a node that mounts {device}:
#     sh <this file> [OUTPUT.raw]
# It only reads metadata -- a LIST rule with -I defer -- and changes no files.
# OUTPUT (default {output}) names every file listed: keep it private
# (it is written mode 0600) and delete it once imported.
set -eu
umask 077
PATH="$PATH:/usr/lpp/mmfs/bin"
device={shlex.quote(device)}
out="${{1:-}}"
[ -n "$out" ] || out={shlex.quote(output)}
case "$out" in *.raw) ;; *) echo "cdm: output must end in .raw" >&2; exit 2 ;; esac

work="$(mktemp -d "${{TMPDIR:-/tmp}}/cdm-policy.XXXXXX")"
trap 'rm -rf "$work"' EXIT HUP INT TERM
cat > "$work/rules" <<'CDM_RULES'
{rules(fileset)}CDM_RULES

cluster="$(mmlscluster -Y | awk -F: '$2 == "clusterSummary" && $3 != "HEADER" {{print $7; exit}}')"
atime="$(mmlsfs "$device" -S -Y |
  awk -F: '$3 != "HEADER" && $8 == "suppressAtime" {{print $9; exit}}')"
if [ -z "$cluster" ] || [ -z "$atime" ]; then
  echo "cdm: could not read the cluster name or the atime setting of $device" >&2
  exit 1
fi

if ! mmapplypolicy "$device" -P "$work/rules" -I defer -f "$work/cdm"{n_flag} -L 1 \\
    > "$work/log" 2>&1; then
  tail -n 20 "$work/log" >&2
  echo "cdm: mmapplypolicy failed; nothing was written" >&2
  exit 1
fi
list="$work/cdm.list.{LIST_NAME}"
[ -f "$list" ] || : > "$list"          # nothing matched: an empty listing
rows="$(wc -l < "$list" | tr -d ' ')"

{{
  echo "# {FORMAT}"
  echo "# device: $device"
  echo "# cluster: $cluster"
  echo "# scope: {scope}"
  echo "# suppress_atime: $atime"
  echo "# fields: {'|'.join(FIELDS)}"
  echo "# times: utc"
  echo "# generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# generator: {generator}"
  cat "$list"
  echo "{END}$rows"
}} > "$out.partial"
mv "$out.partial" "$out"
echo "cdm: wrote $out ($rows entries)" >&2
"""


def instructions(device: str, fileset: str | None, output: str | None) -> str:
    output = output or default_output(device, fileset)
    lines = [
        f"A script to list {'fileset ' + fileset if fileset else 'ALL of ' + device} "
        f"for `cdm import --policy`. To use it:",
        "  1. Save it: cdm policy ... > cdm-list.sh, and read it.",
        f"  2. On a node that mounts {device}, as root: sh cdm-list.sh",
        f"  3. It writes {output} (mode 0600), then: cdm import --policy {output}",
        "It only reads metadata. The listing names every file it covers: keep it "
        "private and delete it after importing.",
    ]
    if not fileset:
        lines.append("WARNING: --whole-filesystem lists every user's files; the "
                     "index will then hold all of their file names.")
    return "\n".join(lines)


# --- reading ------------------------------------------------------------------

@dataclass(frozen=True)
class Entry:
    inode: int
    gen: int
    snapid: int
    size: int
    mtime: float
    atime: float
    ctime: float
    uid: int
    gid: int
    mode: str
    fileset: str
    pool: str
    nlink: int
    path: str

    @property
    def kind(self) -> str:
        return {"d": "dir", "l": "link"}.get(self.mode[:1], "file")


def parse_time(text: str) -> float:
    """'2026-01-15 12:00:00.000000', UTC as the policy engine writes it -> epoch."""
    fmt = "%Y-%m-%d %H:%M:%S.%f" if "." in text else "%Y-%m-%d %H:%M:%S"
    return datetime.strptime(text, fmt).replace(tzinfo=timezone.utc).timestamp()


def parse_entry(line: str) -> Entry:
    """One listing line. Raises ListingError with the reason if it is malformed."""
    head, sep, path = line.rstrip("\n").partition(" -- ")
    parts = head.split()
    if not sep or len(parts) != 4 or not path:
        raise ListingError(f"not a listing line: {line[:120]!r}")
    values = unquote(parts[3]).split("|")
    if len(values) != len(FIELDS):
        raise ListingError(f"expected {len(FIELDS)} fields, got {len(values)}: "
                           f"{line[:120]!r}")
    f = dict(zip(FIELDS, values))
    try:
        return Entry(
            inode=int(parts[0]), gen=int(parts[1]), snapid=int(parts[2]),
            size=int(f["size"]), mtime=parse_time(f["mtime"]),
            atime=parse_time(f["atime"]), ctime=parse_time(f["ctime"]),
            uid=int(f["uid"]), gid=int(f["gid"]), mode=f["mode"],
            fileset=f["fileset"], pool=f["pool"], nlink=int(f["nlink"]),
            # Percent-encoded bytes, decoded the way os.scandir names files,
            # so imported paths compare equal to scanned ones.
            path=os.fsdecode(unquote_to_bytes(path)))
    except ValueError as exc:
        raise ListingError(f"bad value in {line[:120]!r}: {exc}") from exc


def read_header(lines) -> dict[str, str]:
    """The `# key: value` header. Consumes it from `lines`, an iterator."""
    first = next(lines, "").rstrip("\n")
    sanitized = None
    if first.startswith(SANITIZED):
        # A test fixture from scripts/sanitize_listing.py: same format, with
        # names replaced, and marked so it can never pass for real data.
        sanitized = first[len(SANITIZED):]
        first = next(lines, "").rstrip("\n")
    if first != f"# {FORMAT}":
        raise ListingError(f"not a {FORMAT} file (first line {first[:80]!r}); "
                           f"generate it with `cdm policy`")
    header: dict[str, str] = {}
    for line in lines:
        key, sep, value = line[2:].rstrip("\n").partition(": ")
        if not line.startswith("# ") or not sep:
            raise ListingError(f"malformed header line {line[:80]!r}")
        header[key] = value
        if key == "generator":
            break
    if sanitized is not None:
        header["sanitized"] = sanitized
    for key in ("device", "cluster", "scope", "suppress_atime", "fields", "times"):
        if key not in header:
            raise ListingError(f"header has no {key!r}")
    if header["fields"] != "|".join(FIELDS) or header["times"] != "utc":
        raise ListingError(f"unsupported fields {header['fields']!r} or times "
                           f"{header['times']!r}")
    return header


def read_listing(lines):
    """(header, entries, state) for an iterable of lines.

    Entries are yielded lazily, so a listing of tens of millions of lines is
    never held in memory. Once they are exhausted, state["complete"] is True
    only if the end marker was present and its row count matched: a truncated
    listing ends without one and stays False; a marker that disagrees with the
    count raises ListingError. Anything after the marker raises too.
    """
    it = iter(lines)
    header = read_header(it)
    state = {"complete": False, "rows": 0}

    def entries():
        for line in it:
            if line.startswith(END):
                try:
                    declared = int(line[len(END):].strip())
                except ValueError as exc:
                    raise ListingError(f"bad end marker {line.strip()!r}") from exc
                state["complete"] = declared == state["rows"]
                if not state["complete"]:
                    raise ListingError(f"end marker says {declared} rows, read "
                                       f"{state['rows']}: the listing is damaged")
                if next(it, None) is not None:
                    raise ListingError("data after the end marker")
                return
            state["rows"] += 1
            yield parse_entry(line)

    return header, entries(), state
